sudo: required
services:
    - docker

script:
    - docker build -t mannydesigns/node2 .
    - docker images mannydesigns/node2

before_deploy:
  - docker login -u <username>  -p <userpassword>

deploy:
  provider: script
  script: docker push <dockeruser/nameofproject>
  on:
    branch: master